name: "docs/*.html Builder"

on:
  push:
    branches:
      - master

jobs:
  main:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - run: "gem install haml redcarpet"
      - run: "rake ghpages"
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./

